name: Run PR Agent
on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]
  issue_comment:
    types: [ created ]
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          # Github에서 자동 생성됨
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # AI API Key
          GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}
          # PR이 열릴 때 실행되는 자동 도구를 활성화/비활성화
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"